#version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: javi98/python-api-car-price-ai:1.0.0
    container_name: python-api-car-price-ai-app
    restart: unless-stopped
    # command: fastapi run app/main.py --port 8000 # Production mode
    command: fastapi run app/main.py --port 8000 --reload # Development mode
    ports:
      - 8000:8000
    volumes:
      - ./:/code
    depends_on:
      - db

  db:
    image: mariadb:11.6.2
    container_name: python-api-car-price-ai-db
    restart: unless-stopped
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin:5.2.2
    container_name: python-api-car-price-ai-phpmyadmin
    restart: unless-stopped
    ports:
      - 8085:80
    environment:
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 350M
    depends_on:
      - db

networks:
  python-api-car-price-ai:
    driver: bridge

volumes:
  db-data:
